# Generated by Django 5.2.1 on 2025-06-25 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_alter_usuario_usuario_dtcriacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id_fazenda', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Fazenda')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('proprietario', models.CharField(max_length=50, verbose_name='Proprietário')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('tamanho', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tamanho (ha)')),
            ],
            options={
                'verbose_name': 'Fazenda',
                'verbose_name_plural': 'Fazendas',
            },
        ),
        migrations.CreateModel(
            name='UsuarioFazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_acesso', models.CharField(max_length=20, verbose_name='Nível de Acesso')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fazenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Usuário da Fazenda',
                'verbose_name_plural': 'Usuários das Fazendas',
                'unique_together': {('fazenda', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='fazenda',
            name='usuarios',
            field=models.ManyToManyField(related_name='fazendas', through='core.UsuarioFazenda', to='usuario.usuario'),
        ),
    ]
