# Generated by Django 5.2.1 on 2025-06-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
