# Generated by Django 5.2.1 on 2025-07-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fazenda_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tp_cultura', models.CharField(max_length=2)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=9)),
                ('qtd_cultura', models.IntegerField()),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='core.fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_plantio', models.DateField()),
                ('dt_colheitaPrevista', models.DateField()),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='core.cultura')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='core.talhao')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=500)),
                ('prioridade', models.CharField(choices=[('A', 'Alta'), ('M', 'Média'), ('B', 'Baixa'), ('U', 'Urgente')], max_length=1)),
                ('dt_solicitacao', models.DateField()),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.fazenda')),
            ],
        ),
    ]
