# Generated by Django 5.2.1 on 2025-07-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cultura_talhao_plantio_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultura',
            name='produtividade_media',
            field=models.FloatField(default=1, help_text='kg por hectare'),
            preserve_default=False,
        ),
    ]
