# Generated by Django 5.2.1 on 2025-07-01 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cultura_produtividade_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talhao',
            name='qtd_cultura',
        ),
    ]
