# Generated by Django 5.2.1 on 2025-07-08 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_talhao_qtd_cultura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultura',
            name='fazenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='culturas', to='core.fazenda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='dt_solicitacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
