# Generated by Django 5.2.1 on 2025-07-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cultura_fazenda_alter_tarefa_dt_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultura',
            name='tp_cultura',
            field=models.CharField(choices=[('GC', 'Gramínea Cereal'), ('GR', 'Gramínea Forrageira'), ('LG', 'Leguminosa'), ('PC', 'Planta de Cobertura'), ('FR', 'Frutífera'), ('FB', 'Fibra')], max_length=2),
        ),
    ]
