# Generated by Django 5.2.1 on 2025-07-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cultura_tp_cultura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fazenda',
            name='tamanho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Tamanho (ha)'),
        ),
    ]
