# Generated by Django 5.2.1 on 2025-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_fazenda_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fazenda',
            name='tamanho',
            field=models.FloatField(max_length=20, verbose_name='Tamanho (ha)'),
        ),
    ]
