# Generated by Django 5.2 on 2025-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_nome', models.CharField(max_length=80, unique=True)),
                ('usuario_email', models.EmailField(max_length=80, unique=True)),
                ('usuario_senha', models.CharField(max_length=30)),
                ('usuario_dtCriacao', models.DateField(auto_now_add=True)),
                ('usuario_imagem', models.ImageField(blank=True, upload_to='fotos/usuario')),
            ],
        ),
    ]
