# Generated by Django 5.2 on 2025-06-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_dtCriacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_email',
            field=models.EmailField(max_length=80, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_imagem',
            field=models.ImageField(blank=True, upload_to='fotos/usuario', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_nome',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_senha',
            field=models.CharField(max_length=30, verbose_name='Senha'),
        ),
    ]
